/* Idle Masters V3.2.7 — standalone Dofus bestiary UI */
(function(){
  function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
  function card(m){var levels=m.minLevel===m.maxLevel?m.minLevel:m.minLevel+'–'+m.maxLevel;var hp=m.hpMin===m.hpMax?m.hpMin:m.hpMin+'–'+m.hpMax;return '<div class="card"><div class="row"><div><b>'+esc(m.name)+'</b><div class="mut">Niveau '+esc(levels)+' · Race '+esc(m.raceId)+'</div></div>'+(m.boss?'<span class="pill">Boss</span>':'')+'</div><div class="mobStats"><div class="mobStat"><small class="mut">PV</small><br><b>'+esc(hp)+'</b></div><div class="mobStat"><small class="mut">PA / PM</small><br><b>'+esc(m.pa)+' / '+esc(m.pm)+'</b></div></div><div class="mut" style="font-size:11px">ID Dofus '+esc(m.id)+'</div></div>'}
  function install(data){var page=document.getElementById('collection');if(!page)return;var monsters=Array.isArray(data.monsters)?data.monsters:[];page.innerHTML='<div class="panel"><div class="eyebrow">Encyclopédie Dofus 3</div><h1>Bestiaire Dofus</h1><div class="gold" style="margin-bottom:10px"><b>'+monsters.length+' monstres niveau 1–40</b> · '+esc(data.version||'')+'</div><div style="display:grid;grid-template-columns:1fr 110px;gap:8px"><input id="dofusMobSearch" placeholder="Rechercher un monstre…" style="min-width:0;background:#17130e;color:var(--text);border:1px solid #5e4e37;border-radius:13px;padding:11px"><select id="dofusMobLevel" style="background:#17130e;color:var(--text);border:1px solid #5e4e37;border-radius:13px;padding:11px"><option value="0">Tous niv.</option>'+Array.from({length:40},function(_,i){return '<option value="'+(i+1)+'">Niv. '+(i+1)+'</option>'}).join('')+'</select></div><div id="dofusMobCount" class="mut" style="margin:10px 0"></div><div id="dofusMobList"></div></div>';
    function draw(){var q=document.getElementById('dofusMobSearch').value.toLowerCase().trim(),lv=Number(document.getElementById('dofusMobLevel').value),list=monsters.filter(function(m){return (!q||String(m.name||'').toLowerCase().indexOf(q)>=0)&&(!lv||(m.minLevel<=lv&&m.maxLevel>=lv))});document.getElementById('dofusMobCount').textContent=list.length+' résultat(s) · '+Math.min(300,list.length)+' affiché(s)';document.getElementById('dofusMobList').innerHTML=list.slice(0,300).map(card).join('')}
    document.getElementById('dofusMobSearch').addEventListener('input',draw);document.getElementById('dofusMobLevel').addEventListener('change',draw);draw();
  }
  function boot(){fetch('dofus-bestiary-1-40.json?v=3.2.7',{cache:'no-store'}).then(function(r){if(!r.ok)throw new Error('HTTP '+r.status);return r.json()}).then(install).catch(function(e){var page=document.getElementById('collection');if(page)page.insertAdjacentHTML('afterbegin','<div class="panel bad"><b>Erreur de chargement du Bestiaire Dofus</b><div>'+esc(e.message)+'</div></div>')})}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();