/* Idle Masters V3.3 — Dofus bestiary grouped by family */
(function(){
  function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
  function levels(m){return m.minLevel===m.maxLevel?m.minLevel:m.minLevel+'–'+m.maxLevel}
  function hp(m){return m.hpMin===m.hpMax?m.hpMin:m.hpMin+'–'+m.hpMax}
  function familyName(raceId,list){
    var names=list.map(function(m){return String(m.name||'')});
    var rules=[[/bouftou/i,'Bouftous'],[/tofu/i,'Tofus'],[/arakne/i,'Araknes'],[/piou/i,'Pious'],[/prespic/i,'Prespics'],[/sanglier/i,'Sangliers'],[/craqueleur/i,'Craqueleurs'],[/blop/i,'Blops'],[/gelée/i,'Gelées'],[/bwork/i,'Bworks'],[/chaf/i,'Chafers'],[/larve/i,'Larves'],[/moskito/i,'Moskitos'],[/sousour/i,'Sousouris'],[/scarafeuille/i,'Scarafeuilles'],[/gobelin/i,'Gobelins']];
    for(var r=0;r<rules.length;r++)if(names.some(function(n){return rules[r][0].test(n)}))return rules[r][1];
    var clean=names.filter(function(n){return n&&n.length<45});
    if(clean.length){var words=clean[0].split(/\s+/).filter(function(w){return w.length>3});for(var i=0;i<words.length;i++){var w=words[i];if(clean.filter(function(n){return n.toLowerCase().indexOf(w.toLowerCase())>=0}).length>=Math.min(2,clean.length))return w+'s'} }
    return 'Famille '+raceId;
  }
  function card(m){return '<div class="card" style="margin:7px 0"><div class="row"><div><b>'+esc(m.name)+'</b><div class="mut">Niveau '+esc(levels(m))+'</div></div>'+(m.boss?'<span class="pill">Boss</span>':'')+'</div><div class="mobStats"><div class="mobStat"><small class="mut">PV</small><br><b>'+esc(hp(m))+'</b></div><div class="mobStat"><small class="mut">PA / PM</small><br><b>'+esc(m.pa)+' / '+esc(m.pm)+'</b></div></div></div>'}
  function install(data){
    var page=document.getElementById('collection');if(!page)return;var monsters=Array.isArray(data.monsters)?data.monsters:[];
    var grouped={};monsters.forEach(function(m){var k=String(m.raceId);(grouped[k]||(grouped[k]=[])).push(m)});
    var families=Object.keys(grouped).map(function(k){var ms=grouped[k].sort(function(a,b){return a.minLevel-b.minLevel||String(a.name).localeCompare(String(b.name),'fr')});return {id:k,name:familyName(k,ms),monsters:ms,min:Math.min.apply(null,ms.map(function(x){return x.minLevel})),max:Math.max.apply(null,ms.map(function(x){return x.maxLevel}))}}).sort(function(a,b){return a.min-b.min||a.name.localeCompare(b.name,'fr')});
    page.innerHTML='<div class="panel"><div class="eyebrow">Encyclopédie Dofus 3</div><h1>Familles de monstres</h1><div class="gold" style="margin-bottom:10px"><b>'+monsters.length+' monstres</b> · '+families.length+' familles candidates · niveaux 1–40</div><div class="mut" style="margin-bottom:12px">Les monstres sont regroupés par famille de données (raceId). Les familles servent de base à la future progression par zones.</div><div style="display:grid;grid-template-columns:1fr 110px;gap:8px"><input id="dofusMobSearch" placeholder="Monstre ou famille…" style="min-width:0;background:#17130e;color:var(--text);border:1px solid #5e4e37;border-radius:13px;padding:11px"><select id="dofusMobLevel" style="background:#17130e;color:var(--text);border:1px solid #5e4e37;border-radius:13px;padding:11px"><option value="0">Tous niv.</option>'+Array.from({length:40},function(_,i){return '<option value="'+(i+1)+'">Niv. '+(i+1)+'</option>'}).join('')+'</select></div><div id="dofusMobCount" class="mut" style="margin:10px 0"></div><div id="dofusFamilyList"></div></div>';
    function draw(){var q=document.getElementById('dofusMobSearch').value.toLowerCase().trim(),lv=Number(document.getElementById('dofusMobLevel').value),shown=0,html='';families.forEach(function(f){var ms=f.monsters.filter(function(m){return (!lv||(m.minLevel<=lv&&m.maxLevel>=lv))&&(!q||f.name.toLowerCase().indexOf(q)>=0||String(m.name||'').toLowerCase().indexOf(q)>=0)});if(!ms.length)return;shown+=ms.length;var boss=ms.some(function(m){return m.boss});html+='<details class="card" style="padding:0;overflow:hidden"><summary style="cursor:pointer;list-style:none;padding:14px"><div class="row"><div><div class="eyebrow">Famille</div><b style="font-size:18px">'+esc(f.name)+'</b><div class="mut">'+ms.length+' monstre(s) · niveaux '+f.min+'–'+f.max+'</div></div><div>'+(boss?'<span class="pill">Boss</span> ':'')+'<span class="pill">'+esc(f.id)+'</span></div></div></summary><div style="padding:0 12px 12px;border-top:1px solid #4d402e">'+ms.map(card).join('')+'</div></details>'});document.getElementById('dofusMobCount').textContent=shown+' monstre(s) dans les familles affichées';document.getElementById('dofusFamilyList').innerHTML=html||'<div class="mut">Aucune famille trouvée.</div>'}
    document.getElementById('dofusMobSearch').addEventListener('input',draw);document.getElementById('dofusMobLevel').addEventListener('change',draw);draw();
  }
  function boot(){fetch('dofus-bestiary-1-40.json?v=3.3',{cache:'no-store'}).then(function(r){if(!r.ok)throw new Error('HTTP '+r.status);return r.json()}).then(install).catch(function(e){var page=document.getElementById('collection');if(page)page.insertAdjacentHTML('afterbegin','<div class="panel bad"><b>Erreur de chargement du Bestiaire Dofus</b><div>'+esc(e.message)+'</div></div>')})}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();